In [1]:
import numpy as np

# Задание 1

In [2]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = np.transpose(a)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Задание 2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

Скалярное произведение - это операция над двумя векторами, результатом которой является скаляр, скалярное произведение можно посчитать с помощью np.dot: np.dot(a_centered[:, 0], a_centered[:, 1])

In [6]:
N = np.size(a)
a_centered_sp = np.dot(a_centered[0], a_centered[1])
print(f"Скалярное произведение столбцов массива: {a_centered_sp:,.4f}")
cov = a_centered_sp / (N-1)
print(f"Ковариация признаков: {cov:,.4f}")

Скалярное произведение столбцов массива: 0.9600
Ковариация признаков: 0.1067


# Задание 4

In [ ]:
m = np.transpose(a)
cov_matrix = np.cov(m)
print("Ковариационная матрица:\n", cov_matrix)
print("Выборочная ковариация:", cov_matrix[0][1])