# **Задание на повторение материала

In [2]:
%matplotlib inline
import numpy as np

### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
a = np.array(range(12, 24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
for i in range(2, np.size(a)+1):
    if np.size(a)%i == 0:
        a_new = a.reshape(i, int(np.size(a)//i))
        print(f'{i}*{int(np.size(a)//i)}\n', a_new)

2*6
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
3*4
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
4*3
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
6*2
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
12*1
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [5]:
# длина одной из осей задается циклом, длина второй оси вычисляется автоматически (т.к. задан аргумент '-1')
for i in range(2, np.size(a)+1):
    if np.size(a)%i == 0:
        if np.size(a)>=i:
            a_new = a.reshape(i, -1)
            print(f'{i}*{int(np.size(a)//i)}\n', a_new)
        else:
            a_new = a.reshape(-1, i)
            print(f'{i}*{int(np.size(a)//i)}\n', a_new)


2*6
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
3*4
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
4*3
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
6*2
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
12*1
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Также можно проверить атрибут ndim для данного массива

In [6]:
# массив является одномерным , если у него только одна строка (аналогично списку значений типа list, или [..., ..., ...])
#массив, у которого много строк, но один столбец, это двумерный массив. Python понимает его как список списков
# Для сровнения, двумерный массив 12*1:
print('Двумерный массив 12*1:\n', a_new)
# преобразуем в одномерный столбчатый массив (исходный массив сжат до одной оси, но в памяти хранится в столбчатом стиле):
print('Одномерный массив, хранится как столбец (ф-я ravel с параметром "F")):\n', np.ravel(a_new, 'F'))
print('Одномерный массив, сжат до одной оси(ф-я reshape с параметром "-1"):\n', np.reshape(a_new, -1))
print('Одномерный массив, сжат до одной оси(ф-я flatten):\n', a_new.flatten(order = 'F'))

Двумерный массив 12*1:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Одномерный массив, хранится как столбец (ф-я ravel с параметром "F")):
 [12 13 14 15 16 17 18 19 20 21 22 23]
Одномерный массив, сжат до одной оси(ф-я reshape с параметром "-1"):
 [12 13 14 15 16 17 18 19 20 21 22 23]
Одномерный массив, сжат до одной оси(ф-я flatten):
 [12 13 14 15 16 17 18 19 20 21 22 23]


# 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

Чтобы подтвердить, что размер массивов будет одинаковый, следует их сравнить a.size == a_new.size

In [7]:
a = np.random.normal(loc = 0.0, scale = 1.0, size = (3, 4))
print('Массив 3*4:\n', a)
a_new = a.reshape(-1)
print('Одномерный массив: \n', a_new)

Массив 3*4:
 [[ 1.37278375  0.12677844 -0.09774635 -0.25759434]
 [-0.01464671 -0.08271857 -0.77473478 -0.7689155 ]
 [-0.31392483 -0.01243628 -0.38894185  1.18450924]]
Одномерный массив: 
 [ 1.37278375  0.12677844 -0.09774635 -0.25759434 -0.01464671 -0.08271857
 -0.77473478 -0.7689155  -0.31392483 -0.01243628 -0.38894185  1.18450924]


### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

У метода arange - 3 аргумента (старт, стоп, шаг), шаг может быть отрицательным, можно сделать, следующим образом: np.arange(20, 0, -2)

In [8]:
a = np.arange(1, 20, 2)[::-1]
a

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

В данном случае надо поменять форму массива, b.shape(1, 10), а потом сравнить их атрибуты ndim, и Вы увидите, чем они отличаются.
В данном случае ошибка еще и в том, что массив не включает в себя конечную точку диапазона, в Вашем случае - это 20, а если применить np.arange(20, 1, -2) - то массив исключит 1

In [9]:
b = np.arange(2, 20, 2)[::-1]
b
# массивы отличаются сдвигом значений элементо на единицу

array([18, 16, 14, 12, 10,  8,  6,  4,  2])

### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
b = np.ones((3, 2), int)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [11]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [12]:
v = np.vstack((a, b))
print(v)
print('Размерность нового массива: ', np.size(v))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размерность нового массива:  10


### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


В Numpy для этого есть функция arange

In [13]:
a = np.array(range(0, 12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [16]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [17]:
print('Размер матрицы B:', np.shape(B))

Размер матрицы B: (4, 4)


In [18]:
# Вычисление обратной матрицы для B
d = np.linalg.det(B)
d 
if d == 0:
    print('Определитель матрицы равен НУЛЮ – обратной матрицы НЕ СУЩЕСТВУЕТ.')
else:
    B_1 = np.linalg.inv(B)

Определитель матрицы равен НУЛЮ – обратной матрицы НЕ СУЩЕСТВУЕТ.


### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [19]:
np.random.seed(42)
print(np.random.rand(4))
print(np.random.rand(4))
print(np.random.randint(50))

[0.37454012 0.95071431 0.73199394 0.59865848]
[0.15601864 0.15599452 0.05808361 0.86617615]
35


### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

У функции randint в Numpy есть третий аргумент, который позволяет определить количество случайных чисел в массиве, решение задачи могло быть таким: np.random.randint(0, 16, 16)

In [20]:
c = np.arange(16)
np.random.shuffle(c)
c

array([ 8, 13,  9,  6,  0, 11,  3, 10, 12, 14,  1,  4,  5,  2, 15,  7])

### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [21]:
C = c.reshape(int(np.sqrt(np.size(c))), int(np.sqrt(np.size(c))))
C

array([[ 8, 13,  9,  6],
       [ 0, 11,  3, 10],
       [12, 14,  1,  4],
       [ 5,  2, 15,  7]])

In [22]:
D = C*10 + B
D

array([[ 85, 144, 113,  92],
       [ 14, 160, 116, 222],
       [143, 226, 159, 252],
       [ 82, 142, 362, 372]])

In [23]:
# Определитель матрицы D
d_d = np.linalg.det(D)
d_d

-417018399.99999934

In [24]:
# ранг матрицы D
d_rank = np.linalg.matrix_rank(D)
d_rank

4

In [25]:
# Обратная матрица для D
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00579442, -0.01109294,  0.01129173,  0.00040377],
       [ 0.01049076,  0.00680929, -0.00504371, -0.00324139],
       [ 0.00991625, -0.00099976, -0.00773812,  0.00338618],
       [-0.01237696,  0.00081886,  0.00696636,  0.00054132]])

### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [26]:
D_inv = np.where(D_inv > 0, 1, 0)
D_inv

array([[0, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 1]])

In [27]:
E = np.where(D_inv==1, B, C)
E

array([[  8,  13,  23,  32],
       [ 14,  50,   3,  10],
       [ 23,  14,   1, 212],
       [  5, 122, 212, 302]])