# Пример работы с командами shell

In [1]:
!dir

 Том в устройстве C не имеет метки.
 Серийный номер тома: C265-AF29

 Содержимое папки C:\Users\Nina\Documents\Python Scripts

19.06.2022  11:31    <DIR>          .
19.06.2022  11:31    <DIR>          ..
19.06.2022  11:31    <DIR>          .ipynb_checkpoints
19.06.2022  10:45           316 276 c284f491cef9e6cc00c7348c650f0924.ipynb.txt
19.06.2022  10:45         1 554 964 housing.csv
19.06.2022  10:45         2 560 071 housing_prepared.csv
19.06.2022  11:30               589 Les1.ipynb
19.06.2022  10:43    <DIR>          Архив
19.06.2022  11:35               247 Горячие клавиши Jupyter.txt
               5 файлов      4 432 147 байт
               4 папок  671 335 800 832 байт свободно


# Магические команды

In [3]:
%lsmagic
#вывод списка магических команд

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [ ]:
### %run [file_name.py] - запуск питоновского файла
### %%time - измеряет время, за которое исполняется код в ячейке
### %%timeit - измеряет время, за которое исполняется отдельая команда
### %load [file_name.py] или %pycat [file_name.py]- загружает код из питоновского файла в ячейку джупитер

# Numpy

In [13]:
import numpy as np
my_arr = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
print(my_arr)
print(my_arr.size)
print(my_arr.shape)
print(my_arr.ndim)
print(my_arr.dtype)
#my_arr1 = my_arr - y_arr1 -это ссылка на массив my_arr. При измении одного массива изменения происходят и в другом
# my_arr1 = my_arr.copy - копирование массива. my_arr1 и my_arr теперь независимы друг от друга

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
10
(5, 2)
2
int32


### Действия над векторами и матрицами (см.файлы курса математики!)

### Модуль numpy.linalg

In [12]:
A = np.array([[1, 6], [2, 8]])
### возведение матрицы в степень, работает только с квадратными матрицами
A_squer = np.linalg.matrix_power(A, 2)
A_squer

array([[13, 54],
       [18, 76]])

In [14]:
### создание единичной матрицы
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
### транспонирование матриц
my_arr = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
np.transpose(my_arr)

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
### Обращение матриц
my_arr = np.array([[1, 2, 3], [6, 8, 11], [7, 8, 9]])
np.linalg.inv(my_arr)

array([[-2.66666667,  1.        , -0.33333333],
       [ 3.83333333, -2.        ,  1.16666667],
       [-1.33333333,  1.        , -0.66666667]])

In [19]:
#Ранг матрицы
np.linalg.matrix_rank(my_arr)

3

In [21]:
#определитель матрицы
np.linalg.det(my_arr)

5.999999999999998

# Автоматическое создание массивов

### Массив из нулей

In [22]:
np.zeros(3)

array([0., 0., 0.])

### Массив из единиц

In [23]:
np.ones(3)

array([1., 1., 1.])

### Массив из диапазона чисел

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [28]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [29]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [38]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [46]:
#генерирует числа кратные 10 в степени
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [49]:
#генерирует случайные числа, аргумент в скобках - это количисево сгенерированных чисел
np.random.sample(10)

array([0.49474209, 0.35284182, 0.03362914, 0.89698497, 0.21822513,
       0.71208903, 0.31732031, 0.65821303, 0.28741153, 0.49141073])

In [52]:
np.random.sample((3, 2))

array([[0.66845604, 0.98882768],
       [0.41007331, 0.98608585],
       [0.91836081, 0.79270064]])

In [53]:
np.random.randn(3, 4)

array([[-0.93457116,  0.06598262,  1.0901977 , -1.30202548],
       [-0.9010359 , -1.46387329, -0.24228388,  0.91648472],
       [ 0.82899345,  1.55691709,  0.72026759,  0.48131319]])

In [55]:
np.random.randint(0, 100, (3, 3))

array([[28, 52, 95],
       [90, 51, 46],
       [57, 78, 38]])

In [57]:
#выбор случайного числа из одномерного массива
a = np.array([28, 52, 95])
np.random.choice(a)

28

In [58]:
np.random.choice(a, 2)

array([95, 95])

In [62]:
### инициализация генератора случайных чисел
#### вывод одних и тех же случайных числел
np.random.seed(42)

In [65]:
np.random.randint(0, 10, 3)

array([2, 6, 7])

In [66]:
np.random.randint(0, 10, 3)

array([4, 3, 7])

## изменение формы массива

In [69]:
a = np.arange(12)
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
# указать только количесво строк
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
# указать только кол-во столбцов
np.reshape(a, (-1, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [77]:
np.resize(a, (2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
b = np.resize(a, (2, 4))
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Cодинение массивов

In [88]:
a = np.zeros((3, 3))
b = np.ones((3, 3))
np.vstack((a, b))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.concatenate((a, b), axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.hstack((a, b))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [91]:
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

### Соединение массивов в третьем измерении (в глубину)

In [92]:
np.dstack([a, b])

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

# Мат.операции над массивами

## Выбор данных их массива

In [95]:
a = np.random.randint(0, 20, 10)
a

array([15, 14, 14, 18, 11, 19,  2,  4, 18,  6])

### срез элементов

In [97]:
a[0:5]

array([15, 14, 14, 18, 11])

### Отбор по условию

In [98]:
a[a >=10]

array([15, 14, 14, 18, 11, 19, 18])

In [101]:
a[(a>=10) & (a % 2 == 0)]

array([14, 14, 18, 18])

In [102]:
a[(a>=10) | (a % 2 == 0)]

array([15, 14, 14, 18, 11, 19,  2,  4, 18,  6])

In [103]:
# возвращает индексы, удовлетворяющие условию
np.where(a > 10)

(array([0, 1, 2, 3, 4, 5, 8], dtype=int64),)

In [104]:
#отбор элементов из массива по маске
a = [1, 2, 3]
b = [4, 5, 6]
np.where([True, False, True], a, b)

array([1, 5, 3])

## Сортировка

In [111]:
a = np.array([[1, 10, 8, 5], [12, 18, 2, 5], [0, 2, 4, 8]])
a

array([[ 1, 10,  8,  5],
       [12, 18,  2,  5],
       [ 0,  2,  4,  8]])

In [116]:
a[[2, 0, 1], :]

array([[ 0,  2,  4,  8],
       [ 1, 10,  8,  5],
       [12, 18,  2,  5]])

In [117]:
#сортирует и выводит массив индексов
a.argsort(axis=0)

array([[2, 2, 1, 0],
       [0, 0, 2, 1],
       [1, 1, 0, 2]], dtype=int64)

In [118]:
#Сортировка по первому столбцу
a[a[:, 0].argsort(), :]

array([[ 0,  2,  4,  8],
       [ 1, 10,  8,  5],
       [12, 18,  2,  5]])

In [120]:
#Сортировка по третьему столбцу
a[a[:, 2].argsort(), :]

array([[12, 18,  2,  5],
       [ 0,  2,  4,  8],
       [ 1, 10,  8,  5]])

## Перемешивание массива

In [121]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.random.shuffle(a)
a

array([5, 8, 3, 1, 9, 6, 7, 4, 2, 0])

In [127]:
b = np.random.randint(0, 100, (3, 3))
b

array([[89, 43, 33],
       [73, 61, 99],
       [13, 94, 47]])

In [129]:
np.random.shuffle(b)
b
#перемешал строки массива

array([[13, 94, 47],
       [89, 43, 33],
       [73, 61, 99]])

## Мат.операции с массивами

In [130]:
#натуральнй логарифм по соснованию e
np.log(a)

C:\Users\Nina\AppData\Local\Temp\ipykernel_10000\1206115851.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([1.60943791, 2.07944154, 1.09861229, 0.        , 2.19722458,
       1.79175947, 1.94591015, 1.38629436, 0.69314718,       -inf])

In [131]:
#Экспонента
np.exp(a)

array([1.48413159e+02, 2.98095799e+03, 2.00855369e+01, 2.71828183e+00,
       8.10308393e+03, 4.03428793e+02, 1.09663316e+03, 5.45981500e+01,
       7.38905610e+00, 1.00000000e+00])

In [132]:
b.sum()

552

In [133]:
b.sum(axis=0)
#суммы по cтолбцам

array([175, 198, 179])

In [134]:
b.sum(axis=1)
#суммы по строкам

array([154, 165, 233])

In [136]:
#поэлементное уможение массивов
a = np.array([[1, 2, 3], [1, 2, 3]])
b = np.array([[2, 2, 2], [1, 1, 1]])
a * b

array([[2, 4, 6],
       [1, 2, 3]])

In [137]:
# умножение на число
a * 10

array([[10, 20, 30],
       [10, 20, 30]])

In [140]:
#Broadcasting (на примере сложения)
# число строк и столбцов не совпадает 
a = np.array([[1, 2], [1, 2]])
b = np.array([2, 2])
a + b # прибавил к каждой строке массива a сроку массива b
# в случае со столбцами прибавляет столбец 1-мерного массива ко всем столбцам многомерного массиа

array([[3, 4],
       [3, 4]])

# Статистические функции

In [152]:
s1 = np.array([1, 2, 3, 3, 1])
s2 = np.array([6, 8, 11, 10, 7])
a = np.vstack((s1, s2))
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [153]:
a.min()

1

In [154]:
a.max()

11

In [157]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [158]:
a.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

In [159]:
a.std()

3.515679166249389

In [160]:
a.std(axis = 0)

array([0.89442719, 1.8547237 ])

# Запись и чтение массива из файла

In [162]:
np.save('a.npy', a)

In [163]:
b = np.load('a.npy')
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])